# Artificial Neural Network - Customer Churn

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
# Reading the data
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# Splitting the dataset into X and Y
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
dataset['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [8]:
# Using Label Encoder for Gender data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:,2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
# One Hot Encoding for Geography data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
# Splitting the data into Training & Testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
# It is important to feature scale any deep learning model.
# Applying feature_scaling to our model.
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

#### BUILDING AN ARTIFICIAL BRAIN

In [14]:
# Building the ANN
ann = tf.keras.models.Sequential()

In [15]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [16]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [17]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))
# For three classes, activation func will be 'softmax'

#### TRAINING THE ANN

In [18]:
# For binary class, loss func is always 'binary_crossentropy'
# For three classes, loss func is always 'categorical_crossentropy'

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
ann.fit(X_train, y_train, batch_size=32, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 146us/sample - loss: 0.5532 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.4853 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.4615 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.4477 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.4381 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.4318 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.4269 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4224 - accuracy: 0.7960
Epoch 9/100
8000/8000 [============

8000/8000 [==============================] - 1s 66us/sample - loss: 0.3333 - accuracy: 0.8640
Epoch 74/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3335 - accuracy: 0.8637
Epoch 75/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3331 - accuracy: 0.8631
Epoch 76/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3333 - accuracy: 0.8634
Epoch 77/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3330 - accuracy: 0.8634
Epoch 78/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3330 - accuracy: 0.8637
Epoch 79/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3330 - accuracy: 0.8643
Epoch 80/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3331 - accuracy: 0.8669
Epoch 81/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3328 - accuracy: 0.8650
Epoch 82/100
8000/8000 [==========================

In [21]:
# Anything has to be in double [[]] for predict.

print(ann.predict(scalar.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


In [29]:
# Another example

print(ann.predict(scalar.transform([[0, 1, 0, 550, 1, 27, 1, 32000, 1, 0, 0, 28000]])) > 0.5)

[[False]]


In [30]:
predictions = ann.predict(X_test)
predictions = (predictions > 0.5)
print(np.concatenate((predictions.reshape(len(predictions), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test, predictions)